discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

discussion/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'

urlpatterns = [
    path('',views.index, name="index"),
    path('<int:todoitem_id>/', views.todoitem, name = 'viewtodoitem'),
    path('register', views.register, name='register'),
    path('change_password', views.change_password, name="change_password"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('add_task', views.add_task, name="add_task"),
    path('<int:todoitem_id>/edit', views.update_task, name="update_task"),
    path('<int:todoitem_id>/delete', views.delete_task, name="delete_task")
]

discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ToDoItem(models.Model):
    task_name = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField('date created')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

discussion/todolist/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20)
    password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
    task_name = forms.CharField(label='Task Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label='Task Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)
    status = forms.CharField(label='Status', max_length=50)

# class RegisterForm(UserCreationForm):
#     first_name = forms.CharField(max_length=50)
#     last_name = forms.CharField(max_length=50)
#     email = forms.EmailField
#     class Meta:
#         model=User
#         fields = ['username','first_name', 'last_name','email','password1','password2'] 

class RegisterForm(UserCreationForm):
    email = forms.EmailField(
    max_length=100,
    required = True,
    help_text='Enter Email Address',
    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
    )
    first_name = forms.CharField(
    max_length=100,
    required = True,
    help_text='Enter First Name',
    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
    )
    last_name = forms.CharField(
    max_length=100,
    required = True,
    help_text='Enter Last Name',
    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
    )
    username = forms.CharField(
    max_length=200,
    required = True,
    help_text='Enter Username',
    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
    )
    password1 = forms.CharField(
    help_text='Enter Password',
    required = True,
    widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
    )
    password2 = forms.CharField(
    required = True,
    help_text='Enter Password Again',
    widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'}),
    )
    check = forms.BooleanField(required = True)

    class Meta:
        model = User
        fields = [
        'username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'check',
        ]

discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

from .models import ToDoItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm


def index(request):
    # return HttpResponse("Hello from the views.py file")
    # todoitem_list = ToDoItem.objects.all()
    # output = ', '.join([todoitem.task_name for todoitem in todoitem_list])
    # return HttpResponse(output)
    todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
    context = {
        'todoitem_list': todoitem_list,
        'user': request.user
    }

    return render(request, "todolist/index.html", context)


def todoitem(request, todoitem_id):
    # response = "You are viewing the details of %s"
    # return HttpResponse(response % todoitem_id)
    # todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
    todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

    # return render(request, "todolist/todoitem.html", todoitem)
    return render(request, "todolist/todoitem.html", model_to_dict(todoitem))


def register(request):
    # if request.method == 'POST':
    #     form = RegisterForm()

    # return render(request, "todolist/register.html", { 'form': form})

    # if request.method == 'GET':
    #     form  = RegisterForm()
    #     context = {'form': form}
    #     return render(request, "todolist/register.html", context)
    if request.method == 'POST':
        form  = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todolist:login')
    else:
        form = RegisterForm()
    return render(request, "todolist/register.html", {'form': form})
    # else:
    #     print('Form is not valid')
    #     context = {'form': form}
    #     return render(request, "todolist/register.html", context)

   

def change_password(request):
    is_user_authenticated = False

    user = authenticate(username="johndoe", password = "john1234")
    print(user)

    if user is not None:
        authenticated_user = User.objects.get(username='johndoe')
        authenticated_user.set_password("johndoe1")
        authenticated_user.save()
        is_user_authenticated = True

    context = {
        "is_user_authenticated": is_user_authenticated
    }

    return render(request, "todolist/change_password.html")

def login_view(request):

    context = {}

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid() == False:
            form = LoginForm()

        else:
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            context = {
                "username": username,
                "password": password,
            }

            if user is not None:
                login(request, user)
                return redirect("todolist:index")
            else:
                context = {
                    "error": True
                }
    return render(request, "todolist/login.html", context)


    # username ="johndoe"
    # password = "johndoe1"
    # user = authenticate(username=username, password=password)
    # print(user)

    # if user is not None:
    #     login(request, user)
    #     return redirect("todolist:index")
    
    # else: 
    #     return render(request, "todolist/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("todolist:index")

def add_task(request):

    context = {}
    if request.method == 'POST':
        form = AddTaskForm(request.POST)

        if form.is_valid() == False:
            form = AddTaskForm()

        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']

            duplicates = ToDoItem.objects.filter(task_name=task_name)

            if not duplicates:
                ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(),user_id=request.user.id)
                return redirect("todolist:index")
            
            else:
                context = {
                    "error": True
                }

    return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):

    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    context = {
        "user": request.user,
        "todoitem_id": todoitem_id,
        "task_name": todoitem[0].task_name,
        "desciption": todoitem[0].description,
        "status": todoitem[0].status
    }

    if request.method == 'POST':
        form = UpdateTaskForm(request.POST)

        if form.is_valid() == False:
            form = UpdateTaskForm()
        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']

            if todoitem:
                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status

                todoitem[0].save()
                return redirect("todolist:index")
            else:
                context = {
                    "error": True
                }
    return render(request, "todolist/update_task.html", context)        

def delete_task(request, todoitem_id):
    todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
    return redirect("todolist:index")

discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Add A Task</h1>
                {% if error == True %}
                    <p class="text-danger">Duplicate task found</p>
                {% endif %}
                <form action="{% url 'todolist:add_task' %}" method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="task_name">Task Name: </label>
                        <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required> 
                    </div>
                    <div class="mb-3">
                        <label for="description">Description: </label>
                        <textarea class="form-control" id="description" type="text" name="description" value="{{ description }}" maxlength="50" required></textarea> 
                    </div>
                    <div class="text-center">
                        <input class="btn btn-success" type="submit" value="Add Task">
                    </div>

                </form>
            </div>
        </div>
    </div>
    {% endblock %}

discussion/todolist/templates/todolist/change_password.html
{%  if is_user_authenticated == False  %}
    <h1>Invalid User Credentials</h1>
    <p>Check if the username or password is correct</p>
{%  else  %}
    <h1>User Password Successfully updated</h1>
    <p>The password has been Successfully updated</p>

{%endif%}

discussion/todolist/templates/todolist/index.html
{% extends 'base.html'%}

{%block title%}Home{%endblock%}

{%block content%}
    {% if todoitem_list and user.is_anonymous == False %}
        <h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}} </h1>
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My tasks</h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                {% for todoitem in todoitem_list %}
                    <li class="list-group-item">
                        <a href="{% url 'todolist:viewtodoitem' todoitem.id %}"
                         class="text-decoration-none">{{todoitem.task_name}}</a>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    {% elif user.is_anonymous == True %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
       

    {%else%}
        <p>No tasks have been created</p>
    {%endif%}
{%endblock%}

discussion/todolist/templates/todolist/login.html
{% extends 'base.html'%}

{% block title %}Login{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Login</h1>
            {% if error == True %}
                <p class="text-danger">Invalid user credentials, please check your username and passwod</p>
            {% endif %}
            <form action="{% url 'todolist:login' %}" method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="username">Username: </label>
                    <input class="form-control" id="username" type="text" name="username" value="{{username}}" maxlength="20" required>
                </div>

                <div class="mb-3">
                    <label for="password">Password: </label>
                    <input class="form-control" id="password" type="text" name="password" value="{{password}}" maxlength="20" required>
                </div>

                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="login">
                </div>

            </form>
        </div>

    </div>
</div>
{% endblock%}

<!-- {% if is_user_authenticated == False %}
<h1>Something went wrong</h1>
<p>Please contact your administrator or reset password</p>
<a href="{% url 'todolist:index' %}">Back to index page</a>

{%endif%} -->

discussion/todolist/templates/todolist/register.html
{% extends 'base.html'%}

{% block title %}Register{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Register</h1>
            <!-- {% if error == True %}
                <p class="text-danger">Passwords do not match. </p>
            {% endif %} -->
            <form action="{% url 'todolist:register' %}" method="post">
                {% csrf_token %}
                {% for field in form %}

                {% endfor %}
                        <div class="mb-3">
                                <label for="username">Username: </label>
                                <!-- <input class="form-control" id="username" type="text" name="username" value="{{username}}" maxlength="20" required> -->
                                {{form.username}}
                        </div>
                        <div class="mb-3">
                                <label for="username">First Name: </label>
                                <!-- <input class="form-control" id="first_name" type="text" name="first_name" value="{{first_name}}" maxlength="20" required> -->
                                {{form.first_name}}
                        </div>
                        <div class="mb-3">
                                <label for="username">Last Name: </label>
                                <!-- <input class="form-control" id="last_name" type="text" name="last_name" value="{{last_name}}" maxlength="20" required> -->
                                {{form.last_name}}
                        </div>
                        <div class="mb-3">
                                <label for="username">Email: </label>
                                <!-- <input class="form-control" id="email" type="text" name="email" value="{{email}}" maxlength="20" required> -->
                                {{form.email}}
                        </div>

                        <div class="mb-3">
                                <label for="password">Password: </label>
                                <!-- <input class="form-control" id="password1" type="password" name="password1" maxlength="20" required> -->
                                {{form.password1}}
                        </div>
                        <div class="mb-3">
                                <label for="password">Confirm Password: </label>
                                <!-- <input class="form-control" id="password2" type="password" name="password2"  maxlength="20" required> -->
                                {{form.password2}}
                        </div>
           
                        

                        <div class="text-center">
                        <input class="btn btn-success" type="submit" value="Register">
                        </div>

            </form>
        </div>

    </div>
</div>
{% endblock%}


<!-- {% if is_user_registered == True %}
        <h1>Duplicate User Found!</h1>
        <p>A duplicate user has been found, user creation unsuccesful</p>
{% else %}
        <h1>User Successfully Created</h1>
        <p>The account for {{first_name}} {{last_name}} has been Successfully created</p>
{% endif %}
 -->

discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="text-center my-3">
    <h1>{{task_name}}</h1>
    <h3>Description</h3>
    <p>{{description}}</p>
    <h3>Status</h3>
    <p>{{status}}</p>

    <button class="bn btn-primary mx-1 text-decoration-none">
        <a href="{% url 'todolist:update_task' id%}" class="text-light text-decoration-none">Update Task</a>
    </button>
    <button class="bn btn-primary mx-1 text-decoration-none">
        <a href="{% url 'todolist:delete_task' id%}" class="text-light text-decoration-none">Delete Task</a>
    </button>
    <button class="bn btn-primary mx-1 text-decoration-none">
        <a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back to tasks</a>
    </button>

</div>
{% endblock %}

discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
    {% if user.is_anonymous == False %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Update Task</h1>
                {% if error == True %}
                    <p class="text-danger">Task not found</p>
                {% endif %}
                <form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="task_name">Task Name: </label>
                        <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required> 
                    </div>
                    <div class="mb-3">
                        <label for="description">Description: </label>
                        <textarea class="form-control" id="description" type="text" name="description" value="{{ description }}" maxlength="200" required></textarea> 
                    </div>
                    <div class="mb-3">
                        <label for="status">Status: </label>
                        <input class="form-control" id="status" type="text" name="status" value="{{ status}}" maxlength="50" required> 
                    </div>
                    <div class="text-center">
                        <input class="btn btn-success" type="submit" value="Update Task">
                    </div>

                </form>
            </div>
        </div>
    </div>
    {% else %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
    {% endif %}
{% endblock %}